dev_comments = false
skip_readme = false

[Hunspell]
extra_dictionaries = ["spellcheck.dic"]
lang = "en_US"
search_dirs = ["."]
skip_os_lookups = true
use_builtin = true

[Hunspell.quirks]
allow_concatenation = true
